[package]
name = "wismut"
version = "0.1.0"
authors = ["bismuth-party"]
description = "Telegram group statistics bot"

[dependencies]
clap = "2.32.0"
futures = "0.1.23"
hyper = "0.12"
reqwest = "0.8.7"
telegram-bot = "0.6"
tokio-core = "0.1.1"
toml = "0.4"
